Update deque data structure
* Update Deque code in C
* Update Deque docs

diff --git a/01_Data_Structure/src/mk b/01_Data_Structure/src/mk
--- a/01_Data_Structure/src/mk
+++ b/01_Data_Structure/src/mk
@@ -47,5 +47,12 @@ else
 	echo "Check out your code"
 fi
 
-
+gcc jh_deque.c ${COMPILE_FLAG} -o jh_deque
+if [ $? -eq 0 ]; then
+	./jh_deque
+else
+	echo
+	echo "Compile Failed..."
+	echo "Check out your code"
+fi
 
