Update Search algorithm docs and code
* update search algorithm docs
* Update search algorithm cod in C
** Sequential search
** Binary search

diff --git a/01_Data_Structure/src/mk b/01_Data_Structure/src/mk
--- a/01_Data_Structure/src/mk
+++ b/01_Data_Structure/src/mk
@@ -3,7 +3,6 @@
 COMPILE_FLAG="-g"
 
 g++  jh_stack.cc ${COMPILE_FLAG} -o jh_stack
-
 if [ $? -eq 0 ]; then
 	./jh_stack.exe
 else
@@ -24,6 +23,15 @@ fi
 gcc jh_singly_linked_list.c ${COMPILE_FLAG} -o jh_singly_linked_list
 if [ $? -eq 0 ]; then
 	./jh_singly_linked_list
+else
+	echo
+	echo "Compile Failed..."
+	echo "Check out your code"
+fi
+
+gcc jh_search.c ${COMPILE_FLAG} -o jh_search
+if [ $? -eq 0 ]; then
+	./jh_search
 else
 	echo
 	echo "Compile Failed..."
